# @package __global__

framework:
  sample_factory:
    device: gpu
    batch_size: 16384
    decorrelate_experience_max_seconds: 150
    train_for_env_steps: 9999999999999

  pufferlib:
    device: cuda
    vectorization: multiprocessing
    train:
      total_timesteps: 50_000_000
      num_envs: 216
      num_workers: 72
      env_batch_size: 72
      batch_size: 4096
      minibatch_size: 4096
      zero_copy: False
      update_epochs: 1
