# @package __global__

framework:
  sample_factory:
    device: gpu
    batch_size: 16384
    decorrelate_experience_max_seconds: 150
    train_for_env_steps: 9999999999999

  pufferlib:
    device: cuda
    vectorization: multiprocessing
    train:
      total_timesteps: 50_000_000
      num_envs: 1000
      num_workers: 250
      env_batch_size: 250
      batch_size: 4000
      minibatch_size: 4000
      zero_copy: False
      update_epochs: 1
