# @package env

defaults:
  - mettagrid/mettagrid


game:
  objects:
    agent:
      initial_energy: 250
    altar:
      cooldown: 10
      use_cost: 100

  num_agents: 16
  map:
    layout:
      rooms_x: 4
      rooms_y: 2
    room:
      width: 10
      height: 10
      border: 1
      objects:
        agent: 2
        generator: 1
        converter: 1
        altar: 1
        wall: 5
