_target_: env.griddly.power_grid.power_grid_env.PowerGridEnv

name: "GDY-PowerGrid"

global_features: [
  "agent:energy:initial",
  "agent:energy:max",
  "agent:energy:regen",
  "altar:coldown",
  "altar:cost",
  "attack:damage",
  "attack:freeze_duration",
  "charger:cooldown",
  "charger:energy",
  "cost:attack",
  "cost:frozen",
  "cost:jump",
  "cost:move:predator",
  "cost:move:prey",
  "cost:move",
  "cost:rotate",
  "cost:shield:upkeep",
  "cost:shield",
  "generator:cooldown",
  "gift:energy",
]

grid_features: [
  "agent",
  "altar",
  "charger",
  "generator",
  "wall",
  "agent:dir",
  "agent:energy",
  "agent:frozen",
  "agent:id",
  "agent:inv:1",
  "agent:inv:2",
  "agent:inv:3",
  "agent:shield",
  "agent:species",
  "altar:ready",
  "charger:bonus",
  "charger:input:1",
  "charger:input:2",
  "charger:input:3",
  "charger:output",
  "charger:ready",
  "generator:ready",
  "generator:resource"
]
