# @package env

defaults:
  - mettagrid/mettagrid


game:
  objects:
    agent:
      initial_energy: 250
    altar:
      cooldown: 10
      use_cost: 10

  no_energy_steps: 1000
  tile_size: 8
  num_agents: 4
  map:
    layout:
      rooms_x: 2
      rooms_y: 2
    room:
      width: 100
      height: 100
      border: 1
      objects:
        agent: 1
        generator: 5
        converter: 10
        altar: 1
        wall: 30
