_target_: env.meltingpot.harvest.HarvestEnv
name: "MeltingPot-Harvest"

global_features: [
  "ready_to_shoot",
  "collective_reward"
]

grid_features: [
  "grid_ob_0",
  "grid_ob_1",
  "grid_ob_2",
  "grid_ob_3",
  "grid_ob_4",
  "grid_ob_5",
  "grid_ob_6",
  "grid_ob_7",
]

