# @package env

defaults:
  - mettagrid/mettagrid

game_builder:
  num_agents: 100
  tile_size: 8
  map:
    layout:
      rooms_x: 5
      rooms_y: 5
    room:
      width: 20
      height: 20
      border: 1
      objects:
        agent: 4
        altar: 1
        converter: 2
        generator: 4
        wall: 20
