# @package env

defaults:
  - mettagrid/mettagrid

game_builder:
  width: 100
  height: 100
  tile_size: 16

  objects:
    agent:
      count: 100

    altar:
      count: 20
    converter:
      count: 30
    generator:
      count: 200
