# @package env

defaults:
  - mettagrid/mettagrid

game_builder:
  num_agents: 100
  tile_size: 8
  map:
    room:
      width: 100
      height: 100
      border: 1
      objects:
        agent: 100
        altar: 20
        converter: 30
        generator: 200
        wall: 1000
