# @package env

defaults:
  - mettagrid/mettagrid

game_builder:
  num_agents: 20
  map:
    layout: [ [ "room", "room" ], [ "room", "room" ] ]

    room:
      width: 20
      height: 20
      border: 1
      objects:
        agent: 5
        altar: 1
        converter: 3
        generator: 10
        wall: 40
