# @package env

defaults:
  - mettagrid/mettagrid

game:
  num_agents: 20
  map:
    layout:
      rooms: [
        [ "base", "wild_1", "base" ],
        [ "wild_2", "center", "wild_2" ],
        [ "base", "wild_1", "base" ],
      ]

    wild_1:
      width: 10
      height: 15
      border: 0
      objects:
        agent: 0
        altar: 1
        converter: 1
        generator: 5
        wall: 5

    wild_2:
      width: 15
      height: 10
      border: 0
      objects:
        agent: 0
        altar: 1
        converter: 1
        generator: 5
        wall: 5

    center:
      width: 10
      height: 10
      border: 0
      objects:
        agent: 0
        altar: 2
        converter: 5
        generator: 10
        wall: 20

    base:
      width: 15
      height: 15
      border: 1
      objects:
        agent: 5
        altar: 1
        converter: 3
        generator: 5
        wall: 5
