# @package env

defaults:
  - mettagrid/mettagrid

game_builder:
  width: 40
  height: 40

  objects:
    agent:
      count: 20

    altar:
      count: 5
    converter:
      count: 10
    generator:
      count: 50
