# @package env

defaults:
  - mettagrid/mettagrid


game:
  num_agents: 5
  map:
    room:
      width: 25
      height: 25
      border: 1
      objects:
        agent: 5
        altar: 1
        converter: 3
        generator: 15
        wall: 60
