# @package env

defaults:
  - mettagrid/mettagrid

game_builder:
  width: 25
  height: 25

  objects:
    agent:
      count: 5

    altar:
      count: 1
    converter:
      count: 3
    generator:
      count: 15
