defaults: [ mettagrid/mettagrid@env ]

env_builder:
  width: 20
  height: 20

  objects:
    wall:
      density: 0.01
    altar:
      count: 1
      cost: 100
    agent:
      count: 2
    generator:
      count: 5
    converter:
      count: 10


