# @package env

name: "GDY-MettaGrid"
_target_: env.griddly.mettagrid.gym_env.MettaGridGymEnv
max_action_value: 10

game_builder:
  _target_: env.griddly.mettagrid.game_builder.MettaGridGameBuilder
  obs_width: 11
  obs_height: 11
  max_steps: 1000
  tile_size: 16
  num_agents: ???

  objects:
    agent:
      initial_energy: 100
      max_energy: 500
      max_inventory: 5
      freeze_duration: 10
      hp: 1
      upkeep:
        shield: 1

    altar:
      hp: 30
      cooldown: 2
      cost: 100

    converter:
      hp: 30
      cooldown: 2
      energy_output: 50
      cost: 0

    generator:
      hp: 30
      cooldown: 50
      initial_resources: 100
      cost: 0

    wall:
      density: 0.01
      hp: 10

  actions:
    move:
      cost: 0
    rotate:
      cost: 0
    jump:
      cost: 3
    shield:
      cost: 0
    drop:
      cost: 1
    use:
      cost: 0
    attack:
      cost: 5
      damage: 5

  map:
    # _target_: env.griddly.mettagrid.level_builder.MettaGridLevelBuilder

    layout: [ [ room ]]

    room:
      # _target_: env.griddly.mettagrid.level_builder.MettaGridRoomBuilder
      width: 25
      height: 25
      num_agents: 5
      objects:
        agent: 5
        altar: 1
        converter: 3
        generator: 15
        wall: 10
