name: "GDY-MettaGrid"
_target_: env.griddly.mettagrid.gym_env.MettaGridGymEnv

game_builder:
  _target_: env.griddly.mettagrid.game_builder.MettaGridGameBuilder
  obs_width: 11
  obs_height: 11
  max_steps: 1000
  tile_size: 16

  width: ???
  height: ???

  objects:
    agent:
      count: ???
      initial_energy: 100
      max_energy: 500
      max_inventory: 5
      freeze_duration: 10
      hp: 1
      upkeep:
        shield: 1

    altar:
      hp: 30
      count: ???
      cooldown: 2
      cost: 100

    converter:
      hp: 30
      count: ???
      cooldown: 2
      energy_output: 50
      cost: 0

    generator:
      hp: 30
      count: ???
      cooldown: 50
      initial_resources: 100
      cost: 0

    wall:
      density: [0.0, 0.15]
      hp: 10

  actions:
    move:
      cost: 0
    rotate:
      cost: 0
    jump:
      cost: 3
    shield:
      cost: 0
    drop:
      cost: 1
    use:
      cost: 0
    attack:
      cost: 5
      damage: 5


global_features: [
  "conf:agent:energy:initial",
  "conf:agent:energy:max",
  "conf:altar:cooldown",
  "conf:altar:cost",
  "conf:attack:damage",
  "conf:attack:freeze_duration",
  "conf:charger:cooldown",
  "conf:charger:energy",
  "conf:cost:attack",
  "conf:cost:frozen",
  "conf:cost:jump",
  "conf:cost:move",
  "conf:cost:rotate",
  "conf:cost:shield:upkeep",
  "conf:cost:shield",
  "conf:generator:cooldown",
  "conf:gift:energy",
]

grid_features: [
  "agent",
  "altar",
  "charger",
  "generator",
  "wall",
  "agent:dir",
  "agent:energy",
  "agent:frozen",
  "agent:id",
  "agent:inv:1",
  "agent:inv:2",
  "agent:inv:3",
  "agent:shield",
  "agent:species",
  "altar:ready",
  "charger:bonus",
  "charger:input:1",
  "charger:input:2",
  "charger:input:3",
  "charger:output",
  "charger:ready",
  "generator:ready",
  "generator:resource"
]

actions: [
  "rotate",
  "move",
  "jump",
  "use",
  "gift",
  "shield",
  "attack"
]
max_action_value: 10
