# @package env

name: "GDY-MettaGrid"
_target_: env.mettagrid.mettagrid_env.MettaGridEnv
# _target_: env.griddly.mettagrid.gym_env.MettaGridGymEnv
max_action_value: 10

hidden_features:
  grid_obs: [
    "agent:energy",
    "agent:hp",
  ]

game:
  # _target_: env.griddly.mettagrid.game_builder.MettaGridGameBuilder
  obs_width: 11
  obs_height: 11
  max_steps: 5000
  tile_size: 16
  num_agents: ???
  no_energy_steps: 500

  objects:
    agent:
      initial_energy: 250
      max_energy: 250
      max_inventory: 5
      freeze_duration: 10
      energy_reward: False
      hp: 1
      mortal: False
      upkeep.time: 0
      upkeep.shield: 1
      use_cost: 0

    altar:
      hp: 30
      cooldown: 2
      use_cost: 100

    converter:
      hp: 30
      cooldown: 2
      energy_output.r1: 100
      energy_output.r2: 10
      energy_output.r3: 1

    generator:
      hp: 30
      cooldown: 5
      initial_resources: 30
      use_cost: 0

    wall:
      hp: 10

  actions:
    move:
      cost: 0
    rotate:
      cost: 0
    jump:
      cost: 3
    shield:
      cost: 0
    transfer:
      cost: 0
    use:
      cost: 0
    attack:
      cost: 5
      damage: 5
    gift:
      cost: 0

  map:
    # _target_: env.griddly.mettagrid.level_builder.MettaGridLevelBuilder

    layout:
      rooms_x: 1
      rooms_y: 1

    room:
      # _target_: env.griddly.mettagrid.level_builder.MettaGridRoomBuilder
      width: 25
      height: 25
      num_agents: 5
      objects:
        agent: 5
        altar: 1
        converter: 3
        generator: 15
        wall: 10

kinship:
  # _target_: env.wrapper.reward_sharing.TeamRewardSharing
  team_size: 1
  team_reward: 0
