# @package env

defaults:
  - mettagrid

game:
  # _target_: env.griddly.mettagrid.game_builder.MettaGridGameBuilder
  obs_width: 11
  obs_height: 11
  max_steps: 5000
  tile_size: 16
  num_agents: ???

  objects:
    agent:
      initial_energy: [50, 500]
      max_energy: [200, 500]
      max_inventory: [3, 10]
      freeze_duration: [5, 20]
      energy_reward: False
      hp: 1
      mortal: True
      upkeep:
        time: 1
        shield: [0, 3]

    altar:
      hp: [10, 50]
      cooldown: [2, 5]
      cost: [50, 300]

    converter:
      hp: [10, 50]
      cooldown: [2, 5]
      energy_output: [50, 200]
      cost: 0

    generator:
      hp: [10, 50]
      cooldown: [3, 10]
      initial_resources: [5, 50]
      cost: 0

    wall:
      density: 0.01
      hp: [3, 20]

  actions:
    move:
      cost: [0, 2]
    rotate:
      cost: [0, 1]
    jump:
      cost: [1, 5]
    shield:
      cost: [0, 2]
    drop:
      cost: [0, 2]
    use:
      cost: [0, 2]
    attack:
      cost: [3, 10]
      damage: [3, 10]

  map:
    # _target_: env.griddly.mettagrid.level_builder.MettaGridLevelBuilder

    layout:
      rooms_x: 1
      rooms_y: 1

    room:
      # _target_: env.griddly.mettagrid.level_builder.MettaGridRoomBuilder
      width: 25
      height: 25
      num_agents: 5
      objects:
        agent: 5
        altar: 1
        converter: 3
        generator: 15
        wall: 10

kinship:
  # _target_: env.wrapper.reward_sharing.TeamRewardSharing
  team_size: [1, 5]
  team_reward: [0.0, 1.0]
