
sweep:
  method: bayes
  name: sweep
  metric:
    goal: maximize
    name: environment/episode_return
  # Nested parameters name required by WandB API
  parameters:
    train:
      parameters:
        ent_coef: {
          'distribution': 'log_uniform_values',
          'min': 1e-3,
          'max': 5e-2,
        }
        gamma: {
          'values': [0.90, 0.925, 0.95, 0.975, 0.99],
        }
        gae_lambda: {
          'values': [0.90, 0.925, 0.95, 0.975, 0.99],
        }
        learning_rate: {
          'distribution': 'log_uniform_values',
          'min': 1e-4,
          'max': 1e-1,
        }
        batch_size: {
          'values': [4096, 8192, 16384, 32768, 65536],
        }
        minibatch_size: {
          'values': [1024, 2048, 4096, 8192, 16384],
        }
        bptt_horizon: {
          'values': [1, 2, 4, 8, 16],
        }
