
rnn:
    rnn_num_layers: 1
    rnn_size: 512
    rnn_type: gru


obj_attn_agent:
    rnn: rnn,
    normalize_input: True
    agent: object_attn_agent
    agent_attention_combo: mean
    agent_fc_layers: 3
    agent_fc_size: 512

feature_agent:
    rnn: rnn,
    normalize_input: True
    agent: feature_agent
    agent_fc_size: 512

feature_attn_agent:
    rnn: rnn,
    normalize_input: True
    agent: feature_attn_agent
    agent_fc_size: 512

sandbox_agent:
    rnn: rnn,
    normalize_input: True
    agent: sandbox_agent
    agent_fc_layers: 1
    agent_fc_size: 512
    agent_embedding_size: 64
    agent_embedding_layers: 1

