defaults:
  - framework: sample_factory/train
  - agent: agent
  - env: mettagrid/a20_b4_40x40

cmd: ???
experiment: ???

wandb:
  track: False
  project: metta
  entity: platypus
  group: platypus
  name: ${experiment}
