train_base:

prod_training:
  defaults: [ __self__,  train_base]
  with_wandb: True
  wandb_user: platypus
  wandb_project: sample_factory
  batch_size: 16384
  decorrelate_experience_max_seconds: 150
  train_for_env_steps: 9999999999999

sandbox_training:
  defaults:
    - train_base
    - agent: sandbox_agent
  with_wandb: False
  batch_size: 1024
  decorrelate_experience_max_seconds: 0
  train_for_env_steps: 9999999999999
