# @package framework

defaults:
  - pufferlib/train

train:
  total_timesteps: 50_000_000
  learning_rate: 0.00175
  num_envs: 1
  num_workers: 1
  env_batch_size: 1
  update_epochs: 1
  gamma: 0.925
  gae_lambda: 0.99
  ent_coef: 0.0018
  bptt_horizon: 8
  # batch_size: 65536
  batch_size: 1024
  # minibatch_size: 2048
  minibatch_size: 1024
  compile: False
  anneal_lr: False
  checkpoint_interval: 10
