# @package framework

_target_: rl_framework.sample_factory.sample_factory.SampleFactoryFramework

train_dir: ${data_dir}/sample_factory

sample_factory:
  experiment: ${experiment}
  load_checkpoint_kind: latest
  train_dir: ${data_dir}/sample_factory

  nonlinearity: elu
  normalize_input: False

  seed: 0

  recurrence: 256
  rollout: 256

  aux_loss_coeff: 0
  value_loss_coeff: 0.976
  exploration_loss: symmetric_kl
  exploration_loss_coeff: 0.002

  policy_initialization: orthogonal

  learning_rate: 0.0001
  max_policy_lag: 50

