# @package framework

_target_: rl_framework.sample_factory.sample_factory.SampleFactoryFramework

sample_factory:
  experiment: ${experiment}
  train_dir: ./train_dir/sample_factory
  nonlinearity: elu
  load_checkpoint_kind: latest
  normalize_input: False
  seed: 0

  aux_loss_coeff: 0
  recurrence: 256
  rollout: 256
  value_loss_coeff: 0.976
  exploration_loss: symmetric_kl
  exploration_loss_coeff: 0.002
  policy_initialization: orthogonal
  learning_rate: 0.0001
  max_policy_lag: 50

