# @package agent

_target_: agent.metta_agent.MettaAgent

observation_encoders:
  grid_obs:
    feature_names: []

    normalize_features: False
    label_dim: 4
    output_dim: 512
    layers: 4

  global_vars:
    feature_names: []

    normalize_features: False

    label_dim: 4
    output_dim: 8
    layers: 2

  last_action:
    feature_names: [ last_action_id, last_action_val ]

    normalize_features: False

    label_dim: 4
    output_dim: 8
    layers: 2

  last_reward:
    feature_names: [ last_reward ]

    normalize_features: False

    label_dim: 4
    output_dim: 8
    layers: 2

  kinship:
    feature_names: [ kinship ]

    normalize_features: False

    label_dim: 4
    output_dim: 8
    layers: 2

fc:
  layers: 3
  output_dim: 512

decoder:
  _target_: agent.decoder.Decoder


core:
  _target_: sample_factory.model.core.ModelCoreRNN

  rnn_type: gru
  rnn_num_layers: 1
  rnn_size: 512

