_target_: agent.feature_dict_agent.FeatureDictAgent

defaults:
  - rnn/gru


num_grid_features: 50
add_position: True

embedding_size: 64
embedding_layers: 3
embedding_norm: False
embedding_skip: False
projection_layers: 1

fc_layers: 3
fc_size: 512
fc_norm: False
fc_skip: False


