_target_: agent.feature_agent.FeatureAgent

defaults:
  - rnn/gru

normalize_features: True

globals_embedding:
  label_dim: 4
  input_dim: 1
  output_dim: 8
  layers: 2
  norm: False
  skip: False

grid_embedding:
  label_dim: 4
  output_dim: 512
  layers: 4
  norm: False
  skip: False

fc_layers: 3
fc_size: 512
fc_norm: False
fc_skip: False


