_target_: agent.feature_dict_agent.FeatureDictAgent

defaults:
  - rnn/gru

normalize_features: False
globals_emb_size: 8
globals_emb_layers: 2
globals_emb_norm: False
globals_emb_skip: False

grid_emb_size: 512
grid_emb_layers: 4
grid_emb_norm: False
grid_emb_skip: False

fc_layers: 3
fc_size: 512
fc_norm: False
fc_skip: False


