# @package env

defaults:
  - mettagrid/mettagrid


game:
  num_agents: 8
  map:
    layout:
      rooms_x: 4
      rooms_y: 2
    room:
      width: 10
      height: 10
      border: 1
      objects:
        agent: 1
        generator: 0
        converter: 0
        altar: 0
        wall: 10
