# @package framework

defaults:
  - sample_factory/defaults

aux_loss_coeff: 0
recurrence: 256
rollout: 256
value_loss_coeff: 0.976
exploration_loss: symmetric_kl
exploration_loss_coeff: 0.002
policy_initialization: orthogonal
learning_rate: 0.0001
max_policy_lag: 50
seed: 0
with_wandb: True
